services:
  - type: web
    name: ecuanomia-dashboard
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn tasas_ecuanomia_dash:server
    healthCheckPath: /
    autoDeploy: true
